# SwiftLint Configuration for PlaylistOrganizer

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - line_length

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - overridden_super_call
  - prohibited_interface_builder
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_type_annotation
  - unused_closure_parameter
  - unused_enumerated
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import

# Line length
line_length:
  warning: 120
  error: 200

# File length
file_length:
  warning: 500
  error: 1000

# Function length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10

# Identifier name
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60

# Type name
type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 40
    error: 60

# Excluded paths
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData
  - PlaylistOrganizer.xcodeproj
  - PlaylistOrganizer.xcworkspace

# Included paths
included:
  - Sources
  - Tests

# Custom rules
custom_rules:
  # Test naming convention
  test_naming:
    name: "Test Naming Convention"
    regex: '^test[A-Z][a-zA-Z0-9]*$'
    match_kinds:
      - function
    message: "Test functions should start with 'test' followed by a capital letter"
    severity: warning

  # Turkish comment convention
  turkish_comments:
    name: "Turkish Comments"
    regex: '//.*[çğıöşüÇĞIİÖŞÜ]'
    match_kinds:
      - comment
    message: "Turkish characters in comments are allowed"
    severity: info
